### ISSUE TITLE
Benchmark `drop_assets` of `TrappistDropAssets` 

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/trappist#113]
follow up to https://github.com/paritytech/trappist/pull/109

**Motivation**

`drop_assets` of  `TrappistDropAssets`  currently returns weight 0 to the Executor, which is innacurate.

it does a few storage checks (which are not weightless), then it calls `drop_assets` implementation of `pallet-xcm` (which is also still unbenchmarked and returns `0`) 
ref:
- https://github.com/paritytech/polkadot/issues/3735 
- https://github.com/paritytech/polkadot/blob/88013730166ba90745ae7c9eb3e0c1be1513c7cc/xcm/pallet-xcm/src/lib.rs#L1308

so we need to benchmark everything inside `for asset in multi_assets { ... }` and add that to whatever `pallet-xcm`'s `drop_assets` returns.

https://github.com/paritytech/trappist/blob/098634ea6ffe0ce24caba9f12fc76a677b9ec197/primitives/xcm/src/lib.rs#L114-L119

**Comment by stiiifff** [comment]
@pawanbisht62 Any ETA ?

**Comment by pawanbisht62** [comment]
Hi @stiiifff, as of now I'm working on bridges-task-force. I guess I won't be able to complete this next week either.

**Comment by pawanbisht62** [comment]
We cannot benchmark this as it is. We have to benchmark it in the pallet where TrappistDropAssets will be used.

Reason:

1. FRAME benchmarking only works for pallets.
2. TrappistDropAssets type is generic. So it cannot be generically benchmarked since the results depend on the concrete generic types

So can we close or hold this one for now?

cc: @stiiifff @bernardoaraujor
