### ISSUE TITLE
[Trappist on Rococo] Configure Council

### ISSUE THREAD

**Issue by stiiifff** [paritytech/trappist#142]
- Initialize council members to the 6 pre-funded accounts
- Configure pallet
  - `MotionDuration` is currently 3 minutes. Is this too short ?
  - `SetMembersOrigin` is not set currently. Set to `EnsureRoot`.

**Comment by hbulgarini** [comment]
>MotionDuration is currently 3 minutes. Is this too short ?

Initially i thought 48 hours. I think is enough.

**Comment by hbulgarini** [comment]
> SetMembersOrigin is not set currently. Set to EnsureRoot.

This is something that is out of the scope of the deploy because the SetMembersOrigin was introduced in the release 0.9.39 and we will deploy the release 0.9.37 which ensures that members can only be added by root origin:

Actually the `set_members` call from the collectives pallet is already matching the origin to be root:

```rust
		pub fn set_members(
			origin: OriginFor<T>,
			new_members: Vec<T::AccountId>,
			prime: Option<T::AccountId>,
			old_count: MemberCount,
		) -> DispatchResultWithPostInfo {
			ensure_root(origin)?;
			if new_members.len() > T::MaxMembers::get() as usize {
				log::error!(
					target: LOG_TARGET,
					"New members count ({}) exceeds maximum amount of members expected ({}).",
					new_members.len(),
					T::MaxMembers::get(),
				);
			}
                                 ....

```

Issue to configure SetMemebersOrigin: https://github.com/paritytech/trappist/issues/147
