### ISSUE TITLE
Check why testing with benchmark is taking so long.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#214]
It seems that after #206, running the tests with benchmark feature is taking more than the double of it used to be.

**Comment by kalaninja** [comment]
We used to compile and run tests for trappist only. After #206 both trappist and stout are compiled and tested. We can probably try to reimplement feature flags to become able to compile trappist and stout separately. This will also allow to compare the compilation process for both and make sure that compilation artifacts are reused properly.

**Comment by kalaninja** [comment]
I reintroduced feature flags with #241. Currently not running tests for stout, since it doesn't have much. There also was a problem with not enough space to collect cache after running tests during `test` stage, was fixed in #241 too. Also the building time will improve after polkadot version upgrade, because `hostperfcheck` feature became option. (In 0.9.37 it cannot be disabled and it brings kusama runtime in scope).

The only issue that remains unsolved is the github cache size limit of 10gb per repository. Cache size of a single build is `6gb (tests) + 1.2gb (check) = 7.2gb`.  If we have 2 branches using different cache keys (currently `main` and `xcmv3-dev`) they eliminate each others cache.
