### ISSUE TITLE
Asset registry

### ISSUE THREAD

**Issue by stiiifff** [paritytech/trappist#51]
Currently, Trappist's XCM configuration makes a bold assumption that the local's Assets pallet will be configured with the same asset ID as assets on Statemine which acts as reserve for any assets configured over there: https://github.com/paritytech/trappist/blob/2ef44e00e1abed0c02aeeffb4e4bdb5210141908/runtime/src/xcm_config.rs#L119-L143. This is a rather simplistic (and error-prone) logic.

- Moonbeam uses an AssetManager pallet: https://github.com/PureStake/moonbeam/blob/master/pallets/asset-manager/src/lib.rs
- Acala uses an AssetRegistry pallet (from ORML): https://github.com/open-web3-stack/open-runtime-module-library/tree/master/asset-registry; an the Unknown Tokens pallet (ORML): https://github.com/open-web3-stack/open-runtime-module-library/tree/master/unknown-tokens

We should implement a mechanism similar to an asset manager / registry so that only registered foreign assets are considered for reserve-based transfer operations.

**Comment by bernardoaraujor** [comment]
@Wiezzel is going away on vacation, so we agreed I'll take this one

**Comment by bernardoaraujor** [comment]
Writing this down to register some findings, using Moonbeam as a reference implementation:

Moonbeam's [`ForeignFungiblesTransactor`](https://github.com/PureStake/moonbeam/blob/dc0730e938a5b029f363d09fef2cd0d5a7e34be8/runtime/moonbeam/src/xcm_config.rs#L109) is what we use as reference for our [`StatemineFungiblesTransactor`](https://github.com/paritytech/trappist/blob/80d297bee4e76aabd3c71349cd5de685b315ba6a/runtime/src/xcm_config.rs#L125):
```
// The non-reserve fungible transactor type
// It will use pallet-asset-manager, and the Id will be matched against AsAssetType
pub type ForeignFungiblesTransactor = FungiblesAdapter<
	// Use this fungibles implementation:
	Assets,
	// Use this currency when it is a fungible asset matching the given location or name:
	(
		ConvertedConcreteAssetId<
			AssetId,
			Balance,
			AsAssetType<AssetId, AssetType, AssetManager>,
			JustTry,
		>,
	),
	// Do a simple punn to convert an AccountId20 MultiLocation into a native chain account ID:
	LocationToAccountId,
	// Our chain's account ID type (we can't get away without mentioning it explicitly):
	AccountId,
	// We dont allow teleports.
	Nothing,
	// We dont track any teleports
	(),
>;
--------------------
/// Means for transacting assets from Statemine.
/// We assume Statemine acts as reserve for all assets defined in its Assets pallet,
/// and the same asset ID is used locally.
/// (this is rather simplistic, a more refined implementation could implement
/// something like an "asset manager" where only assets that have been specifically
/// registered are considered for reserve-based asset transfers).
pub type StatemineFungiblesTransactor = FungiblesAdapter<
	// Use this fungibles implementation:
	Assets,
	// Use this currency when it is a fungible asset matching the given location or name:
	ConvertedConcreteAssetId<
		AssetId,
		Balance,
		AsPrefixedGeneralIndex<StatemineAssetsPalletLocation, AssetId, JustTry>,
		JustTry,
	>,
	// Convert an XCM MultiLocation into a local account id:
	LocationToAccountId,
	// Our chain's account ID type (we can't get away without mentioning it explicitly):
	AccountId,
	// We don't track any teleports of `Assets`.
	Nothing,
	// We don't track any teleports of `Assets`.
	CheckingAccount,
>;
```

Part of the solution is to replace the `ConvertAssetId` generic of `ConvertedConcreteAssetId` from `AsPrefixedGeneralIndex<StatemineAssetsPalletLocation, AssetId, JustTry>` to `AsAssetType<AssetId, AssetType, AssetManager>`, where `AssetManager` is an instance of [`pallet_asset_manager`](https://github.com/PureStake/moonbeam/blob/master/pallets/asset-manager/src/lib.rs).

**Comment by bernardoaraujor** [comment]
I started writing a solution here: https://github.com/paritytech/trappist/tree/51-asset-registry

`pallet-asset-registry` is vaguely inspired by Moonbeam's `pallet-asset-manager`, but much simpler (their solution involves 2 instances of `pallet-assets` and some EVM-related complexity that doesn't apply here).

`pallet-asset-registry` has two symmetrical storage items:
- `AssetIdMultiLocation`: a mapping of `AssetId`->`MultiLocation`
- `AssetMultiLocationId`: a mapping of `MultiLocation`->`AssetId`

Here, `AssetId` represents the asset id in Trappist's `pallet-assets`, and `MultiLocation` represents the foreign asset location (Statemine in the demo).

`pallet-asset-registry` is tighly coupled with `pallet-assets`.

`pallet-asset-registry` has three extrinsics, all of which can only be called by  `ForeignAssetModifierOrigin`:
- `register_foreign_asset`: creates a new association between a local `AssetId` and a foreign `MultiLocation`, and creates the local asset by calling `pallet_assets::Pallet::<T>::force_create()` with `Root` as origin. The user is responsible for choosing the `AssetId` to be used, and also to correctly provide the foreign asset's `MultiLocation` and metadata. 
- `change_foreign_asset`: associates a new `MultiLocation` to some pre-existing `AssetId`.
- `destroy_foreign_asset`: cleans up the association between some `AssetId` and its `MultiLocation`, and destroys the local asset by calling `pallet_assets::Pallet::<T>::destroy()` with `Root` as origin.

On Trappist's `xcm_config.rs`,  `StatemineFungiblesTransactor` was renamed to `ForeignFungiblesTransactor` and the naive `AsPrefixedGeneralIndex` [was replaced with `AsAssetMultiLocation`](https://github.com/paritytech/trappist/blob/ff6a9823265a695b3c477b4b5cb26a6338a1cc65/runtime/src/xcm_config.rs#L129), which [implements `xcm_executor::traits::Convert<MultiLocation, AssetId>`](https://github.com/paritytech/trappist/blob/ff6a9823265a695b3c477b4b5cb26a6338a1cc65/primitives/xcm/src/lib.rs#L9).

I did one brief successful test via PolkadotJS by manually creating a sufficient Asset on Statemine, creating the associated Asset on Trappist and making a few reserve transfers from Statemine to Trappist.

However I want to write more extensive unit testing for the pallet and perhaps some tests via [parachains-integration-tests](https://github.com/paritytech/parachains-integration-tests) as well.

The pallet also hasn't been benchmarked yet.

**Comment by stiiifff** [comment]
Cool. I agree with the direction from a high-level perspective.
Re. the `destroy_foreign_asset`, this seems a bit dangerous .. or do you check if there is no account balance(s) associated with this asset (local supply is zero) ?
Maybe we could add `freeze_foreign_asset` (and related unfreeze) operation ?

**Comment by bernardoaraujor** [comment]
I simplified the implementation by removing the calls to `pallet_assets::Pallet::<T>::force_create()` and `pallet_assets::Pallet::<T>::destroy()`. Now, `pallet-asset-registry` works from the assumption that asset creation and destruction is independently managed by `pallet-assets`.

That is possible because before registering a new `AssetId`->`MultiLocation` association, we [check if the asset exists](https://github.com/paritytech/trappist/blob/6957a62898fa354cfaa019059c3232969de76bef/pallets/asset-registry/src/lib.rs#L82) in `pallet-assets`.

Unfortunately, there seems to be no function in the `Fungibles` trait implementations that allows for an easy way to check whether an asset exists on the `pallet-assets`. So I had to stick with the tight coupling strategy so we can call  [`pallet_assets::Pallet::<T>::maybe_total_supply(asset_id)`](https://github.com/paritytech/substrate/blob/23bb5a6255bbcd7ce2999044710428bc4a7a924f/frame/assets/src/functions.rs#L62).

@stiiifff can you elaborate on `freeze_foreign_asset`? Would that be done to avoid some undefined XCM behavior? Is there some reason we should do this on `pallet-asset-registry`, and not directly on `pallet-assets` (like `create`/`destroy`)?

**Comment by stiiifff** [comment]
Regarding the existence check, you could maybe use the `minimum_balance` function of the `fungibles::Inspect` trait (check that it's non-zero). This would allow a more loosely-coupled dependency than the direct one to `pallet-assets`.
Re. the `freeze_foreign_asset`, I think we agreed that it's not needed on the asset registry (should be handled directly on the assets pallet).

**Comment by bernardoaraujor** [comment]
@stiiifff is this a reasonable verification?

https://github.com/paritytech/trappist/blob/ab37c61e866df3584a428c91df0bcfc743a8b87e/pallets/asset-registry/src/lib.rs#L135-L145

I want to avoid registering invalid `MultiLocation`s, so I naively wrote this verification based on what we've been doing on the demo setup.

However I wonder if there could be some different `MultiLocation` that's also valid but not being taken into account.

**Comment by bernardoaraujor** [comment]
I'm reopening this issue because the current implementation is flawed (or incomplete at best).

This was discovered while working on #52. The [`trap_local_asset.yml`](https://github.com/paritytech/trappist/blob/bar/52-asset-trap/integration-tests/asset-trap/trap_local_asset.yml) integration test is meant to generate an `Asset Trap` event on a simple (non-derivative) asset by performing a `WithdrawAsset` and nothing else.

With the current state of the Trappist XCM Config, the integration test mentioned above is resulting in a `FailedToTransactAsset("AssetIdConversionFailed")` error.

I modified the XCM Config on the following snippet
https://github.com/paritytech/trappist/blob/0b169b740b95fcee2bbd1d6c041b9a0e740b28a5/runtime/src/xcm_config.rs#L141-L143

so that it looks like the following:
```
pub type AssetTransactors =
	(LocalAssetTransactor, LocalFungiblesTransactor, ReservedFungiblesTransactor);
```

Essentially, this makes `LocalFungiblesTransactor` take execution precedence over `ReservedFungiblesTransactor`.

This allowed the `trap_local_asset.yml` to execute correctly. However, this also broke [`0_reserve_transfer.yml`](https://github.com/paritytech/trappist/blob/master/integration-tests/asset-registry/0_reserve_transfer.yml), which is an integration test for reserve-based transfers with our `Asset Registry` pallet. The integration test breaks during the `limitedReserveTransferAsset` execution, `FailedToTransactAsset("AssetIdConversionFailed")`.

That indicates that the current implementations of  `LocalFungiblesTransactor` and `ReservedFungiblesTransactor` are somehow conflicting with eachother, and whatever Transactor takes execution precedence gets to execute correctly while breaking the other.

Needs further investigation.

**Comment by stiiifff** [comment]
@bernardoaraujor That's great insight. I think it still makes more sense to have `ReservedFungiblesTransactor` before the `LocalFungiblesTransactor`. What is needed though is a custom `Matcher` implementation for the `ReservedFungiblesTransactor` that links with the `AssetRegistry` so that assets that have not been registered as reserve assets will not be matched (indeed, the error that you see comes from the fact that the local asset matches with the `ReservedFungiblesTransactor` while it shoudn't, and then there's an error with the asset ID converter). When that's the case, the matching logic will fallback to the `LocalFungiblesTransactor` implementation which will match. Hope that makes sense.

**Comment by bernardoaraujor** [comment]
> a custom `Matcher` implementation for the `ReservedFungiblesTransactor` that links with the `AssetRegistry` so that assets that have not been registered as reserve assets will not be matched

But it turns out we already have that.

The current `Matcher` of `ReservedFungiblesTransactor` is `ConvertedConcreteAssetId`, where its `ConvertAssetId` is [`AsAssetMultiLocation`](https://github.com/paritytech/trappist/blob/b8d0c35092190f40fd53baeed232d62af4b44d28/primitives/xcm/src/lib.rs#L6) (our custom XCM primitive that uses the `AssetRegistry` pallet to make the conversion).

If we check the [implementation of `ConvertedConcreteAssetId`](https://github.com/paritytech/polkadot/blob/3711c6f9b2a30ab6cc888917ad0bbfa64266d41b/xcm/xcm-builder/src/fungibles_adapter.rs#L63):

```
pub struct ConvertedConcreteAssetId<AssetId, Balance, ConvertAssetId, ConvertBalance>(
	PhantomData<(AssetId, Balance, ConvertAssetId, ConvertBalance)>,
);
impl<
		AssetId: Clone,
		Balance: Clone,
		ConvertAssetId: Convert<MultiLocation, AssetId>,
		ConvertBalance: Convert<u128, Balance>,
	> MatchesFungibles<AssetId, Balance>
	for ConvertedConcreteAssetId<AssetId, Balance, ConvertAssetId, ConvertBalance>
{
	fn matches_fungibles(a: &MultiAsset) -> result::Result<(AssetId, Balance), MatchError> {
		let (amount, id) = match (&a.fun, &a.id) {
			(Fungible(ref amount), Concrete(ref id)) => (amount, id),
			_ => return Err(MatchError::AssetNotFound),
		};
		let what =
			ConvertAssetId::convert_ref(id).map_err(|_| MatchError::AssetIdConversionFailed)?;
		let amount = ConvertBalance::convert_ref(amount)
			.map_err(|_| MatchError::AmountToBalanceConversionFailed)?;
		Ok((what, amount))
	}
}
```

we see that `what = ConvertAssetId::convert_ref(id)` is precisely looking at the `AssetRegistry` pallet. On failure, it returns `MatchError::AssetIdConversionFailed`.

The problem is that when the asset is not registered, the `Matcher` throws an error and the XCM execution halts completely (without ever reaching `LocalFungiblesTransactor`).

If we wrote a custom `Matcher` implementation, eventually we would need to treat the non-registered asset condition. The only way I can imagine to do so is by throwing an error, which would land us into the exact same place we're in now.

**Comment by bernardoaraujor** [comment]
Hiding the comment above as outdated, sorry for the noise.

It turns out we can use `AssetNotFound` and `Unimplemented` errors to bypass the execution of the Transactor.

https://github.com/paritytech/polkadot/blob/3711c6f9b2a30ab6cc888917ad0bbfa64266d41b/xcm/xcm-executor/src/traits/transact_asset.rs#L117

**Comment by stiiifff** [comment]
@bernardoaraujor So I understand we need a custom Matcher impl (to be used with the `ReservedFungiblesTransactor`) that will return `AssetNotFound` if it's not registered in the Asset Registry so that matching will proceed to the `LocalFungiblesTransactor` ?

**Comment by bernardoaraujor** [comment]
> @bernardoaraujor So I understand we need a custom Matcher impl (to be used with the `ReservedFungiblesTransactor`) that will return `AssetNotFound` if the asset being evaluated is not registered in the Asset Registry, so that the matching logic will proceed to the `LocalFungiblesTransactor` ?

yes, that is my current undestanding. I'll implement it soon and report back.
